export default {
	"MUSIC CTRL": "音乐控制台",
	"MIC CTRL": "麦克风控制台",
	"EFFECT CTRL": "Effect控制台",
	
	"EQ MODE": "EQ模块",
	"CLASSICAL": "古典",
	"JAZZ": "爵士",
	"POP": "流行",
	"ROCK": "摇滚",
	"VOCALS": "人声",
	"EQUALIZER": "均衡器",
	"BASS": "BASS",
	"MID": "MID",
	"TREB": "TREB",
	"MUSIC": "音乐",
	"VOL": "音量",
	"COMMON FUNC": "",
	"INPUT": "输出",
	"MUTE": "菜单",
	"COMMON FUNC": "COMMON FUNC",
	
	"PRIORITY": "闪避",
	"FBX": "移频防啸叫",
	"LOW": "低",
	"MID": "中",
	"HIGH": "高",
	"MIC": "麦克风",
	
	"EFFECT": "EFFECT",
	"REVERB VOL": "混响音量",
	"ECHO VOL": "回声音量",
	"REVERB TIME": "REVERB TIME",
	"REPEAT": "REPEAT",
	"DELAY": "DELAY",
}